### ISSUE TITLE
allow specifiying cgroup-manager

### ISSUE THREAD

**Issue by medyagh** [boot2podman/machine#22]
I noticed on mac I cant specify the cgroup-manager like in linux:

podman --cgroup-manager
Error: unknown flag: --cgroup-manager
podman version:

Client:
Version:            1.6.1-dev
RemoteAPI Version:  1
Go Version:         go1.12.9
OS/Arch:            darwin/amd64

Service:
Version:            1.7.1-dev
RemoteAPI Version:  1
Go Version:         go1.12.10
Git Commit:         ce4bf33ccc80819f199bdbb6526b9adee1ad41b0-dirty
Built:              Sat Jan 18 02:01:17 2020
OS/Arch:            linux/amd64

related https://github.com/containers/libpod/issues/5101

could we make boot2podman specify this on server side?

https://github.com/containers/libpod/issues/5101

**Comment by afbjorklund** [comment]
There isn't really a way to configure this, it is set in /etc/containers/libpod.conf for each image.

**Comment by afbjorklund** [comment]
For now we are using cgroupfs for the Tiny Core image, and systemd for the Fedora image.
