### ISSUE TITLE
Error during setup on Windows

### ISSUE THREAD

**Issue by dominic-p** [boot2podman/machine#3]
I ran into an error trying to setup this up on my Windows 10 1803 machine. I used the latest release 0.14. Below is the output from attempting to create a machine and connect to it. It sits at "Waiting for an IP..." for a while and then fails.

It popped up two VirtualBox UAC prompts the first time I ran the create command and I said yes to both.

```
C:\Users\me>podman-machine create box
Creating CA: C:\Users\me\.local\machine\certs\ca.pem
Creating client certificate: C:\Users\me\.local\machine\certs\cert.pem
Running pre-create checks...
(box) Image cache directory does not exist, creating it at C:\Users\me\.local\machine\cache...
(box) No default Boot2Podman ISO found locally, downloading the latest release...
(box) Latest release for github.com/boot2podman/boot2podman is v0.18
(box) Downloading C:\Users\me\.local\machine\cache\boot2podman.iso from https://github.com/boot2podman/boot2podman/releases/download/v0.18/boot2podman.iso...
(box) 0%....10%....20%....30%....40%....50%....60%....70%....80%....90%....100%
Creating machine...
(box) Copying C:\Users\me\.local\machine\cache\boot2podman.iso to C:\Users\me\.local\machine\machines\box\boot2podman.iso...
(box) Creating VirtualBox VM...
(box) Creating SSH key...
(box) Starting the VM...
(box) Check network to re-create if needed...
(box) Windows might ask for the permission to configure a dhcp server. Sometimes, such confirmation window is minimized in the taskbar.
(box) Waiting for an IP...
Error performing create: Error creating machine: Error in driver during machine creation: Maximum number of retries (5) exceeded


C:\Users\me>podman-machine stop box
Stopping "box"...
Machine "box" was stopped.


C:\Users\me>podman-machine start box
Starting "box"...
(box) Check network to re-create if needed...
(box) Windows might ask for the permission to configure a dhcp server. Sometimes, such confirmation window is minimized in the taskbar.
(box) Waiting for an IP...
Maximum number of retries (5) exceeded


C:\Users\me>podman-machine ssh box -- sudo podman version
exit status 255


C:\Users\me>podman-machine ip
Error getting IP address: ssh command error:
command : ifconfig
err     : exit status 255
output  :
```

After the box is created, I can see it in VirtualBox and connect to the console. Here is a screenshot:
![virtualbox_box_06_02_2019_01_04_16](https://user-images.githubusercontent.com/1195080/52330960-b1c2f080-29ab-11e9-8ad6-16b55b4fff64.png)

But, I can't connect or do anything with the box using podman-machine commands.

Thanks for taking a look.

**Comment by afbjorklund** [comment]
You can run with `--debug`, to get some more logging output.

You do have `ssh`, right ? Otherwise maybe try `--native-ssh`

**Comment by dominic-p** [comment]
Thanks for the quick response. I removed the old machine and tried again. This time I ran: `podman-machine create box` from an elevated command prompt, and everything went fine!

I wasn't able to get `--debug` or `--native-ssh` to work with the create command (it said unrecognized flag), but it's working now, so I guess I just need to run it as admin in my case.

Thanks again for your help.

**Comment by afbjorklund** [comment]
Those flags were for the main command:
`podman-machine --debug create pod`

Glad it worked out!
