### ISSUE TITLE
Please clarify that `podman-machine` is not `podman machine`

### ISSUE THREAD

**Issue by jordemort** [boot2podman/machine#31]
Podman now has its own `podman machine` command, which is not deprecated, but the README on this repo is leading people to think that it is, re: https://news.ycombinator.com/item?id=28390870

**Comment by afbjorklund** [comment]
Well, it's a bit hard to predict the future. Supposedly, `podman machine` could have explained that it is not `podman-machine`, but I am happy to clear it up more: https://boot2podman.github.io/
