### ISSUE TITLE
upgrade flag to support latest dev version

### ISSUE THREAD

**Issue by garethahealy** [boot2podman/machine#9]
Would be nice if it was possible on the upgrade option, to say "build-from-source", and it uses the very latest podman from source.

**Comment by afbjorklund** [comment]
This should be possible do with the regular go tools, but this will only build the `podman-machine` tool.
If you want to rebuild the podman.tcz package from libpod upstream, this requires some CI changes...

Currently the ISO is built manually, even though most of the actual building has been automated.
Providing updated packages more often is a possibility, but it will go in the "boot2podman" project.

https://github.com/boot2podman/boot2podman/blob/master/packages/compile_all#L47

https://github.com/boot2podman/boot2podman/blob/master/packages/package_all#L58

The tcz packaging should probably be split out further, but currently it's more of a all-in-one.

For `podman-machine`, we need a flag to pick "dev" or "stable". But for now, all are pre-release.
